#!/bin/bash
# ifs.sh
var1="a+b+c"
var2="d-e-f"
var3="g,h,i"
IFS=+
# The plus sign will be interpreted as a separator.
echo $var1 # a b c
echo $var2 # d-e-f
echo $var3 # g,h,i
echo
IFS="-"
# The plus sign reverts to default interpretation.
# The minus sign will be interpreted as a separator.
echo $var1 # a+b+c
echo $var2 # d e f
echo $var3 # g,h,i
echo
IFS=","
# The comma will be interpreted as a separator.
# The minus sign reverts to default interpretation.
echo $var1 # a+b+c
echo $var2 # d-e-f
echo $var3 # g h i
echo
