#!/bin/bash

# RANDOM returns a different random integer at each invocation.
# Nominal range: 0 - 32767 (signed 16-bit integer).
RANGE=501
MAXCOUNT=100000
count=1
total=0
echo
echo "$MAXCOUNT random numbers:"
echo "-----------------"
while [ "$count" -le $MAXCOUNT ] # Generate 10 ($MAXCOUNT) random integers.
do
 number=$RANDOM
 let " number  %= $RANGE "
 #echo $number
 [ $number -le 250 ] && let "total += 1"
 let "count += 1" # Increment count.
done
echo "---------------total=  $total"
# If you need a random int within a certain range, use the 'modulo' operator.
