#!/bin/bash
#paragraph-space.sh
# Inserts a blank line between paragraphs of a single-spaced text file.
MINLEN=60 # Change this value? It's a judgment call.
while read line # For as many lines as the input file has ...
do
echo "$line" # Output the line itself.
len=${#line}
if [[ "$len" -lt "$MINLEN" && "$line" =~ [*{\.}]$ ]]
then echo # Add a blank line immediately
fi
done
exit
